# Errbit Config
# =============

# The host of your errbit server
host: rp-mon.heroku.com

# The email address which email notifications will be sent from.
email_from: no-reply@rp-mon.heroku.com

# Configure when emails are sent for an error.
# [1,3,7] = 1st, 3rd, and 7th occurence triggers an email notification.
email_at_notices: [1, 10, 100]
